theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Christophe Slim
description: Christophe has a background in computer science from the <a href="https://www.aup.edu/">American University of Paris</a> as well as in IT/IP law from the <a href="https://www.universite-paris-saclay.fr/en">University of Paris Saclay</a>. He has worked as an in-house lawyer and business developer for the French <a href="https://list.cea.fr/en/digital-trust-building-a-more-secure-digital-world/">Atomic and Alternative Energy Commission</a> around the topics of digital trust and currently works for <a href="https://en.innovasjonnorge.no">Innovation Norway</a>, supporting French competitiveness through French-Norwegian collaboration.
